import java.lang.Exception
import kotlin.ArithmeticException

class CalculoMatematico () {

    val a = Int
    val b = Int





    fun divisao (a: Int, b: Int): Int {

        //val ex = ArithmeticException("Divis√£o por zero")

        //if (b != 0) {
            return a / b
        /*} else {
            throw ex
        }
*/






    }

}